apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gitops

images:
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/frontend
    newName: ghcr.io/lingarajkar/boutique-frontend
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/gateway
    newName: ghcr.io/lingarajkar/boutique-gateway
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/auth
    newName: ghcr.io/lingarajkar/boutique-auth
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/product-service
    newName: ghcr.io/lingarajkar/boutique-product-service
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/order-service
    newName: ghcr.io/lingarajkar/boutique-order-service
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/orders
    newName: ghcr.io/lingarajkar/boutique-orders
    newTag: v1
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/user-service
    newName: ghcr.io/lingarajkar/boutique-user-service
    newTag: v1

patches:
  - target:
      kind: StatefulSet
      name: boutique-postgres
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 2Gi